before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - amd64
  main: ./cmd/hkmgr/main.go
archives:
- replacements:
    darwin: Darwin
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - github:
      owner: bensallen
      name: homebrew-hkmgr
    homepage: "https://github.com/bensallen/hkmgr"
    description: "Hkmgr is a virtual machine manager for the hyperkit macOS hypervisor."
    skip_upload: auto
    dependencies:
      - hyperkit