---
version: 2
workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - clean-code:
          requires:
            - setup
      - test:
          requires:
            - clean-code
      - race:
          requires:
            - clean-code
      - compile:
          requires:
            - clean-code
jobs:
  setup:
    macos:
      xcode: 11.3.0
    steps:
      - run:
        name: Configure environment
        command: |
          echo 'export GOPATH=${HOME}/go' >> $BASH_ENV
          echo 'export PATH=${PATH}:${GOPATH}/bin' >> $BASH_ENV
      - run:
          name: Install Golang
          command: brew install golang
      - run:
          name: Install revive
          command: go get -u github.com/mgechev/revive
  clean-code:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - run:
          name: Go mod verify
          command: go mod verify
      - run:
          name: Go mod graph
          command: go mod graph
      - run:
          name: Run go vet
          command: go vet ./cmd/hkmgr ./internal/...
      - run:
          name: Run revive
          command: test -z "$(revive -exclude=vendor/... ./... | grep -v 'should have comment or be unexported')"
      - run:
          name: gofmt
          command: test -z "$(gofmt -s -l cmd internal)"
  test:
    macos:
      xcode: 11.3.0
    environment:
      - CGO_ENABLED: 0
    steps:
      - checkout
      - run:
          name: Test all
          command: go test -mod=vendor -a -ldflags '-s' ./...
      - run:
          name: Test coverage
          command: go test -mod=vendor -cover ./...
  race:
    macos:
      xcode: 11.3.0
    environment:
      - CGO_ENABLED: 1
    steps:
      - checkout
      - run:
          name: Race detector
          command: go test -mod=vendor -race ./...
  compile:
    macos:
      xcode: 11.3.0
    environment:
      - CGO_ENABLED: 0
    steps:
      - checkout
      - run:
          name: build all tools
          command: go build -mod=vendor -a -ldflags '-s' ./...
